name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Clean
      run: make clean

    - name: Test
      run: make test

    - name: Go coverage badge
      uses: tj-actions/coverage-badge-go@v2
      with:
        filename: coverage.out

    - name: Simply check
      run: |
        git status
        git diff

    - name: Build
      run: make local
      # run: make build
    
    - name: Clean to save space
      run: make clean
