name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Clean
      run: make clean

    - name: Test
      run: make test
    
    - name: Generate coverage badges
      run: |
        bash generate-coverage.sh
        ls -l badges

    - name: Upload coverage badges
      id: upload-coverage-badges
      if: ${{ hashFiles('./badges') != '' }}
      uses: peaceiris/actions-gh-pages@v3
      continue-on-error: true
      with:
        deploy_key: ${{ secrets.GH_PAGES_DEPLOY_KEY }}
        external_repository: will8ug/will8ug.github.io
        publish_dir: ./badges
        publish_branch: main
        destination_dir: ms-user-handler/badges

    - name: Build
      run: make local
    
    - name: Clean to save space
      run: make clean
